spring:
  datasource:
    hikari:
      connection-test-query: SELECT 1
      minimum-idle: 1
      connection-timeout: 900000
      jdbc-url: jdbc:postgresql://localhost:5432/api_auth
      username: apiauth
      password: apiauth2019
      driver-class-name: org.postgresql.Driver
      connection-init-sql:

config:
  oauth2:
    keystore: api-auth.pkcs12
    keypass: s3cr3t19
    keyalias: api-auth